version: '3.8'

services:
  # MinIO 对象存储服务
  minio:
    image: minio/minio:latest
    container_name: s3proxy-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # S3 Proxy 应用服务 (使用 H2 数据库)
  s3-proxy:
    build: .
    container_name: s3proxy-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_DEDUPE_BUCKET=dedupe-storage
      - S3_AUTH_ENABLED=true
    depends_on:
      minio:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - s3proxy_data:/app/data

  # MySQL 数据库服务（可选）
  mysql:
    image: mysql:8.0
    container_name: s3proxy-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: s3proxy
      MYSQL_USER: s3proxy
      MYSQL_PASSWORD: s3proxypassword
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles:
      - mysql

  # S3 Proxy 应用服务 (使用 MySQL 数据库)
  s3-proxy-mysql:
    build: .
    container_name: s3proxy-app-mysql
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=s3proxy
      - MYSQL_USERNAME=s3proxy
      - MYSQL_PASSWORD=s3proxypassword
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_DEDUPE_BUCKET=dedupe-storage
      - S3_AUTH_ENABLED=true
    depends_on:
      minio:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - mysql

volumes:
  minio_data:
  mysql_data:
  s3proxy_data: